-- 147_entry_link_log.sql
-- Лог входящих ссылок: «откуда пришёл человек и по какой ссылке».
-- Каждый заход в бота/Mini App пишет строку (платформа, id юзера, сырой
-- start-параметр, распарсенный slug/pid, launch_params) — для отладки
-- потерянных hash в VK и аналитики источников.
-- Таблица была создана на ПРОДЕ прямым DDL вне git; эта миграция фиксирует её
-- в репозитории. IF NOT EXISTS → на проде отработает как no-op.

CREATE TABLE IF NOT EXISTS public.entry_link_log (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform         TEXT NOT NULL,
    platform_user_id TEXT,
    raw_param        TEXT,
    parsed_slug      TEXT,
    parsed_pid       TEXT,
    launch_params    JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_entry_link_log_created ON public.entry_link_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_entry_link_log_puid    ON public.entry_link_log (platform, platform_user_id);

-- GRANTы (роль БД = plusson)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.entry_link_log TO plusson;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO plusson;
